### ISSUE TITLE
kdu_expand fails on images with too little IPTC data

### ISSUE THREAD

**Issue by mel-mason** [bodleian/image-processing#29]
There's currently a a known bug in `kdu_expand` (https://groups.yahoo.com/neo/groups/kakadu_jpeg2000/conversations/messages/7496) which means it deletes 16 bytes from the IPTC data before copying it over. This isn't a problem usually, as we don't keep the expanded tiff file. But if the tiff file has less than 16 bytes of IPTC data, the `kdu_expand` command fails with a `std::bad_alloc` error in the lossless check.

This will be fixed in the next Kakadu release after April 2018. In the meantime, there's a Kakadu code fix in the link above, or if the IPTC data is unnecessary or can be moved to a different box, removing IPTC entirely also fixes it.

**Comment by ahankinson** [comment]
Probably fixed now (October 2018). Closing.
