### ISSUE TITLE
Set up Travis CI for testing

### ISSUE THREAD

**Issue by ahankinson** [bodleian/image-processing#3]
We should do automated testing on this library.

**Comment by mel-mason** [comment]
Should make sure kakadu files are cached: https://docs.travis-ci.com/user/caching

**Comment by mel-mason** [comment]
Error appearing in travis: `/opt/kakadu/kdu_compress: error while loading shared libraries: libkdu_v7AR.so: cannot open shared object file: No such file or directory`

**Comment by ahankinson** [comment]
That will probably need to be in one of the library loading paths... I think maybe `/lib64`?

**Comment by mel-mason** [comment]
I'm now adding it to LD_LIBRARY_PATH, which is what the kakadu docs recommend

**Comment by mel-mason** [comment]
New error: `/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found`. I'll try adding `sudo apt-get install libstdc++6`
