### ISSUE TITLE
Support Pillow 10

### ISSUE THREAD

**Issue by bbarberBPL** [bodleian/image-processing#56]
Greetings from across the pond at the Boston public library. We recently upgraded our derivative processor, which uses this package, to use Pillow 10 and I noticed a couple failures when running our tests coming from  this line in [conversion.py.](https://github.com/bodleian/image-processing/blob/dc4364a6938d2eaf34efbbdbc1b662cae596a81f/image_processing/conversion.py#L140). 

According to the version 10 docs regarding [constants](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#constants) A few constants in this project require changes  including switching `ImageCms.INTENT_PERCEPTUAL` to `ImageCms.Intent.PERCEPTUAL` as referenced on line 140 in `conversions.py` 

Also on Line 55 of `conversions.py` you will need to change `Image.LANCZOS` to  `Image.Resampling.LANCZOS`
 
I just wanted to give you all a heads up for whenever you update to pillow v 10.

**Comment by mel-mason** [comment]
Hi, thanks for letting us know! We're still using Pillow 9.x here, but will want to upgrade eventually, so this will be very useful then. (And if you'd like those changes in the main branch sooner, feel free to submit a pull request)

**Comment by mel-mason** [comment]
This has just been fixed in https://github.com/bodleian/image-processing/pull/57 , and the latest release now uses Pillow 10
